---
# tasks for servers in app role

- name: create base dir for deployed applications
  become: yes
  file: path=/app/www state=directory owner=pi group=pi

- name: install rbenv
  git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv

- name: install ruby-build plugin
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: update bash profile
  lineinfile: dest=~/.bash_profile line='{{ item }}' create=yes
  with_items:
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - 'eval "$(rbenv init -)"'

- name: instal dependencies
  become: yes
  apt: name={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install ruby
  shell: bash -lc 'rbenv install -s 2.3.0'
  register: action
  changed_when: "action.rc != 0"

- name: set default ruby version
  shell: bash -lc 'rbenv global 2.3.0'
  register: action
  changed_when: "action.rc != 0"

- name: config gemrc
  lineinfile: dest=~/.gemrc line='{{ item }}' create=yes
  with_items:
    - 'gem: --no-document'

- name: install bundler
  shell: bash -lc 'gem install bundler'

- name: config gem source
  shell: bash -lc 'bundle config mirror.https://rubygems.org https://gems.ruby-china.org'

- name: update system gem
  shell: bash -lc 'gem update --system'

- name: show ruby versions
  shell: bash -lc 'rbenv versions'
  register: ruby-versions
  notify:
    - show ruby versions

- name: show gem version
  shell: bash -lc 'gem -v'
  register: gem-version
  notify:
    - show gem version
