---
# handlers for servers in app role

- name: show ruby versions
  debug: msg="Ruby Versions => {{ item }}"
  with_items:
    - "{{ ruby-versions.stdout_lines }}"

- name: show gem version
  debug: msg="Gem Versions => {{ item }}"
  with_items:
    - "{{ gem-version.stdout_lines }}"
